app = "your-app-name"  # Change to your preferred app name

[build]
  [build.args]
    PYTHON_VERSION = "3.9"

[env]
  FLASK_ENV = "production"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[mounts]]
  source = "uploaded_images"
  destination = "/app/static/images"
